datasources:
  default:
    url: jdbc:mysql://38.68.51.222:3306/hefemac_warehouse?serverTimezone=America/Mexico_City
    driverClassName: com.mysql.cj.jdbc.Driver
    username: hefemac_admin
    password: admin2020
    schema-generate: UPDATE
    dialect: MYSQL
jpa.default.properties.hibernate.hbm2ddl.auto: update
