micronaut:
  server:
    port: 18080
    context-path: /api/v1/warehouse
  application:
    name: micronaut
datasources:
  default:
    url: jdbc:mysql://localhost:3306/hefemac_warehouse
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: password
    schema-generate: UPDATE
    dialect: MYSQL
jpa.default.properties.hibernate.hbm2ddl.auto: update
